{
 "title": "AWS Kafka Topic(test)",
 "description": "Topic Level Monitoring for AWS MSK (Kafka) from CloudWatch",
 "tags": [
  "AWS",
  "Kafka",
  "Amazon",
  "CloudWatch"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "brokerid",
    "label": "Broker ID",
    "query": "dimension_values($region,AWS/Kafka, BytesInPerSec, Broker ID)"
   },
   {
    "name": "clustername",
    "label": "Cluster Name",
    "query": "dimension_values($region,AWS/Kafka, BytesInPerSec,Cluster Name)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "dimension_values($region,AWS/Kafka, BytesInPerSec,Topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "BytesIn Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$clustername", "Topic": "$topic" },
     "metricName": "BytesInPerSec",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Bytes out Per Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$clustername", "Topic": "$topic" },
     "metricName": "BytesOutPerSec",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "KafkaDataLogsDiskUsed",
   "type": "graph",
   "description": "The number of KafkaDataLogsDiskUsaged_Average.\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "KafkaDataLogsDiskUsed",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "ZooKeeperRequestLatencyMsMean",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "ZooKeeperRequestLatencyMsMean",
     "namespace": "AWS/Kafka",
     "region": "ap-southeast-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "ZooKeeperSessionState",
   "type": "graph",
   "description": "The number of conversions per second for produced messages.\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "ZooKeeperSessionState",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}