{
 "title": "AWS Kafka Cluster",
 "description": "https://docs.aws.amazon.com/msk/latest/developerguide/monitoring.html",
 "tags": [
  "AWS",
  "Kafka",
  "Amazon",
  "CloudWatch"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "clustername",
    "label": "Cluster Name",
    "query": "dimension_values($region,AWS/Kafka, BytesInPerSec,Cluster Name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Controller Count",
   "type": "stat",
   "description": "Only one controller per cluster should be active at any given time.\n",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "ActiveControllerCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency MsMean",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "ZooKeeperRequestLatencyMsMean",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Global Partition Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "GlobalPartitionCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "OfflinePartitionsCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Global Topic Count",
   "type": "graph",
   "description": "Total number of topics across all brokers in the cluster.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "GlobalTopicCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}